### ISSUE TITLE
More intuitive interface

### ISSUE THREAD

**Issue by swissspidy** [pluginkollektiv/publish-confirm#8]
As seen on the Make blogs:

<img width="295" alt="screen shot 2015-09-24 at 17 24 59" src="https://cloud.githubusercontent.com/assets/841956/10077618/5fbd701a-62e1-11e5-9659-6be87e664c51.png">
<img width="292" alt="screen shot 2015-09-24 at 17 25 04" src="https://cloud.githubusercontent.com/assets/841956/10077617/5fb7f2a2-62e1-11e5-882c-b7d750028957.png">

Easy via JS:

```
jQuery(document).ready( function($) {
    $('#matt-ays-publish').click( function() {
        $('#publishing-action').fadeToggle('fast');
    });
});
```

**Comment by Zodiac1978** [comment]
+1 from me

**Comment by Drivingralle** [comment]
I like the alert box after you clicked publish. Because it makes you think after you clicked it. 

You may want to save the post, but you hit publish. The alert prevents accidental publishing very well. 
As a seasoned author you know that you have to check it at some point in time, so you maybe pre-check it even you don't want to publish right now.

And you can confirm the alert by hitting enter on the keyboard, so it's done quickly.

**Comment by swissspidy** [comment]
I guess I should have written down my reasons for this issue before we end up in a long discussion. Sorry about that!

@Drivingralle made some valid points, so let's have a look at them.

> I like the alert box after you clicked publish. Because it makes you think after you clicked it.

When I created this issue I thought about the plugin's users and how I first reacted to this proposed checkbox. When I click publish and an alert dialog pops up, it confuses me and also makes me a bit angry. Such alerts usually tell me "You did something wrong!" and give me a _bad feeling_.

A simple and friendly "Are you sure?" checkbox on the other hand gives me a _better feeling_ because it's _a more natural part of the publishing workflow_. It makes me think "OK, am I sure I want to publish this?".
We're familiar with this procedure from things like ToS. Therefore I know that checking it means I agree with all the "consequences" of publishing this post.

> You may want to save the post, but you hit publish. The alert prevents accidental publishing very well.

I think a checkbox does that too. I mean, there isn't even a button you could accidentally click on.

> As a seasoned author you know that you have to check it at some point in time, so you maybe pre-check it even you don't want to publish right now.

_Maybe_. Maybe not. We don't know until we've tested this. Even if that would be the case for the majority of people, we could do something about it, like unchecking the checkbox after a certain time or when the content has changed again.

> And you can confirm the alert by hitting enter on the keyboard, so it's done quickly.

So _maybe_ you accidentally hit enter even though you don't want to publish it right now, simply because we're so stressed by alert dialogs and just want them to go away quickly.

**Comment by glueckpress** [comment]
Late to the party, but a couple of thoughts:

**1. This would need introduction.**
Some sort of pointer to the new location/implementation when a person visits the Edit screen for the first time after update. Otherwise the positive effect of not being “hit in the face” by a modal would likely turn into negative surprise (“Where’s my feature?”).

**2. More precise copy.**
“Are you sure?” is kind of generic. Sure of what? The fact the string is placed next to a checkbox does not indicate which exact functionality it relates to. I propose to go with the already existing string “Are you sure you want to publish this now?”, or come up with an entirely new one, like e.g. **“Publish this now, $display_name?”**.

**3. Optional redesign.**
Maybe a bit over the top, but how about making the redesign optional? We could utilize the _Screen Options_ menu to provide a selection like so:

![bildschirmfoto 2016-08-16 um 10 52 19](https://cloud.githubusercontent.com/assets/308422/17693511/92987c04-639f-11e6-9d85-4cd9b7c4c690.png)

That way we’d give users like @Drivingralle a choice to opt-in to the design they loved. I’m aware about _decisions, not options_, but offering an optional rollback to an old design is pretty common practice. Haven’t thought this entirely through, though, not sure about all possible implications. ;)

**Comment by swissspidy** [comment]
1. Good call.  
  Feature pointers, greyed out submit button, etc. There are many possibilities. Needs testing.
2. Definitely.  
  Haven't proposed any final string, was just a screenshot. Having the user's name in the string would make it more personal though.
3. Understandable.  
  A checkbox at Settings -> Writing would make more sense to me.

**Comment by glueckpress** [comment]
> A checkbox at Settings -> Writing would make more sense to me.
+1

**Comment by bueltge** [comment]
In the context of 
>As the Gutenberg editor introduced in WordPress 5.0 contains a similar functionality, the development of this plugin is discontinued. The plugin only supports the classic editor (works fine even when using WordPress 5.0 with the Classic Editor plugin).

we should leave the current status und close this issue, ok @swissspidy ?
